readthedocs/commonmark.py

CommonMark/common.py
spec.txt

To check if DoS attack is possible against PyCommonMark version you use, create file with content:
```
s <!--> 1234567890123
[a link]()
```
and run `time bin/cmark.py minimal.md`. If it takes about 10 seconds
to parse, then your version os CommonMark is vulnerable.

DoS attack is possible using simple <!--> comment, this pull-request fixes it.

---

CommonMark/test/test-CommonMark.py

The tests now look like this, but expand to give more details when they fail:

Reformat tests so successes aren't so verbose

---

CommonMark/CommonMark.py
CommonMark/common.py
CommonMark/test/test-CommonMark.py

parseNewline threw a list index error when running CommonMark-py
against the 0.22 spec.
I've ported the changes in parseNewline from here:
https://github.com/jgm/commonmark.js/blob/master/lib/inlines.js#L738
Now commonmark-py doesn't error out when running on the new
spec, (though there are many failures) and it still works with
the old spec we're using at the moment.
I've also included more changes from commonmark.js that still work with our spec.

Fix index error when running tests on latest spec

---

CommonMark/CommonMark.py
CommonMark/blocks.py
CommonMark/node.py

I've removed the ExtensionBlock code I saw Luca was working
on. This is because, when running the tests on the CommonMark
0.22 spec, I get 157 failures with the ExtensionBlock code in,
and 129 failures without. So I thought that for now we can leave
it out.

Cleanup / test fixes with new spec

---

CommonMark/blocks.py

When parsing [CommonMark's README](https://github.com/jgm/CommonMark/blob/master/README.md) for example, each line in an indented code block is duplicated.

Fix duplicated lines in IndentedCode

---

CommonMark/CommonMark.py
CommonMark/html.py
CommonMark/test/test-CommonMark.py
setup.py

Because we're converting to strings with `str()`, it's possible
to get errors like this:
> 'ascii' codec can't encode character u'\u2022' in position 47: ordinal
> not in range(128)
Using python-future, we can convert to unicode-compatible strings in
both python 2 and 3.
http://python-future.org/compatible_idioms.html#unicode
We should really have tests for stuff like this.. I will look into
adding that.

Fix python2 unicode error

---

CommonMark/__init__.py
CommonMark/common.py
CommonMark/html.py
CommonMark/tests/run_spec_tests.py

I don't know whether you're interested in supporting python26, or whether these changes cause other issues. On RHEL and Centos 6 systems you're largely stuck with python26.
- Numbered substitutions in string formats.
- re.sub doesn't have flags keyword
- Pass a str to urllib.quote `safe`.
There's a UnicodeWarning, but run_spec_tests.py passes and spec.txt can be parsed.
urllib.py:1268: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
return ''.join(map(quoter, s))
The UnicodeWarning is also present in python 2.7.3 against master, so doesn't appear to be the result of these changes.

run_spec_tests pass on python26 with these changes.

---

.travis.yml

We've had a few requests and PR's for 2.6 support.
There isn't a real reason we can't support it,
so let's add it to Travis so we don't break it.

Add 2.6 to the Travis matrix

---

CommonMark/blocks.py
CommonMark/html.py
CommonMark/inlines.py
CommonMark/node.py
CommonMark/tests/run_spec_tests.py

while `object` is implied as a base class in python 3, without it in python 2, it reverts to old-style classes

Use new-style objects in python 2

---

CommonMark/node.py
CommonMark/tests/unit_tests.py

Makes it slightly easier to iterate over nodes - before, you had to do `iter(ast.walker().nxt, None)`

Make NodeWalker iterable

---

CommonMark/html.py

Is there a reason soft-breaks are not set by parameter?

Set softbreak by parameter

---

CHANGELOG.md
CommonMark/node.py
CommonMark/tests/unit_tests.py

This fixes the bug reported by civalin and adds a regression test.
JavaScript is more flexible about inferring types than Python, which is
what caused this problem.
Closes #66

Fix TypeError: unsupported operand type(s)

---

.travis.yml
CommonMark/cmark.py
CommonMark/tests/test.md
README.rst
setup.py

This changes `cmark.py` to `cmark` and moves the script from
the bin folder to the main package folder. So now it will be checked
by flake8.
I fixed the issue by following the piprot tool's example: declaring
the executable script via setup.py's entry_points instead of scripts.
flake8 also does it this way: https://github.com/PyCQA/flake8/blob/master/setup.py#L58
Closes #59

Fix spurious path in cmark script

---

.travis.yml
setup.py

Addressing this issue:
https://travis-ci.org/rtfd/CommonMark-py/jobs/151256231

Limit flake8 to py2.6-compatible version

---

CHANGELOG.md
CommonMark/blocks.py
CommonMark/inlines.py
spec.txt

Update commonmark spec to 0.27

---

CommonMark/render/html.py

This PR make the `HtmlRenderer` escape behavior customizable by inheritance.

Allows to customize HtmlRenderer escaping behavior

---

CommonMark/__init__.py
CommonMark/main.py
CommonMark/render/rst.py
CommonMark/tests/rst_tests.py
docs/api.rst
docs/rst.rst

I work a lot with Sphinx and often need to convert things from Markdown to reStructuredText. This PR introduces a new renderer for reStructuredText.
Why not use rtfd/recommonmark? That Sphinx extension allows entire documents to be written in Markdown. I've written Sphinx extensions that only need to convert a single paragraph at a time from JSON files.
Previously I've relied on using `pandoc` to convert Markdown to reStructuredText. That's a pain because you need to have it installed locally.
If you don't find this useful for the core library, I can always make a standalone library.

Add a reStructuredText renderer

---

CHANGELOG.md
CommonMark/blocks.py
CommonMark/inlines.py
CommonMark/node.py
CommonMark/render/html.py
README.rst
spec.txt

I also changed a bunch of calls from `re.match()` to `re.search()`,
because `re.match()` only searches from the start of the string, which
isn't how the equivalent javascript code behaves.

update commonmark spec to 0.28

---

CommonMark/node.py
CommonMark/tests/unit_tests.py

The parser produces an AST, which may contain multiple
text nodes in a row, which is difficult to work with.
Example commonmark input:
_unfinished emphasis
For this input the parser produces 2 separate text nodes
for "_" and "unfinished emphasis".
The normalize() method on an AST node will walk through
the tree and concatenate these consecutive text nodes.

Add normalize() method for AST nodes

---

commonmark/common.py
commonmark/inlines.py
commonmark/tests/run_spec_tests.py

This pull-request ensures CommonMark-py does not produce `DeprecationWarning` or `UnicodeWarning` anymore. 
Changes made:
- Use `html.unescape` instead of `html.parser.HTMLParser.unescape` (which is deprecated since Python 3.3) on Python 3.3+
- Use `timeit.default_counter()` instead of `time.clock()` (`time.clock()` is deprecated since Python 3.3+ but `timeit.default_counter()` always use the right method on both Python 2 and 3)
- Don't try to quote the raw string, always quote the utf8 encoded. This remove the `UnicodeWarning` on Python 2.7 while still working on other versions

No warnings

---

commonmark/blocks.py
commonmark/common.py
commonmark/inlines.py
commonmark/node.py
commonmark/normalize_reference.py
commonmark/render/html.py
commonmark/tests/unit_tests.py
commonmark/utils.py
spec.txt

* Updated code to match commonmark/commonmark.js@5eebfd3868b812abb2ba5830ca0cc6c9b638add7
* Add missing Unicode case folding for reference normalization
* Fixed a bug where empty link label was not properly recognized

Synchronize code with upstream commonmark.js 0.29

---

CHANGELOG.md
setup.py

I got the following import error and have been investigating for the reasons:
```
Traceback (most recent call last):
...
File "/home/paul/relaunch/native/eggs/commonmark-0.9.0-py2.7.egg/commonmark/normalize_reference.py", line 16, in <module>
from builtins import str, chr
ImportError: No module named builtins
```
It turns out, that with `future` package below version 0.14.0 one has to import via `from future.builtins import str, chr` whereas newer versions support builtins directly. See also the [changelog of future](https://github.com/PythonCharmers/python-future/blob/master/docs/changelog.rst#changes-in-version-0140-2014-10-02).
With this PR it is now ensured, we have at least version 0.14.0 or better.

Require `future` version to be 0.14.0 or higher

---

CHANGELOG.md
setup.py

We only use future for the `builtins` module which is standard in Python 3.

setup.py: Only require future on Python 2

---

commonmark/render/rst.py
commonmark/tests/rst_tests.py

For list items going across multiple lines, the renderer previously did
not indent the latter lines, which leads to invalid rst (see
https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#bullet-lists;
subsequent list items must line up with the first item).
This commit fixes that by introducing an indent when entering a list
item.
Note that there are still some issues (for example, paragraphs within
list items are still not handled correctly), but this at least seems to
be a step in the right direction.

Support rendering multi-line list items to rst
